# Generated by Django 4.2.5 on 2024-03-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('age_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('age_viagem', models.CharField(max_length=70)),
                ('age_site', models.CharField(blank=True, max_length=180, null=True)),
                ('age_datacadastro', models.CharField(blank=True, max_length=255, null=True)),
                ('age_cnpj', models.CharField(max_length=20)),
                ('age_situacao', models.CharField(choices=[('V', 'Verdadeiro'), ('F', 'Falso')], default='F', max_length=20)),
                ('age_inscricaomunicipal', models.CharField(blank=True, max_length=20, null=True)),
                ('age_cep', models.IntegerField(blank=True, default=0, null=True)),
                ('age_rua', models.CharField(blank=True, max_length=70, null=True)),
                ('age_numero', models.IntegerField(blank=True, default=0, null=True)),
                ('age_bairro', models.CharField(blank=True, max_length=70, null=True)),
                ('age_cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('age_fone', models.IntegerField(blank=True, default=0, null=True)),
                ('age_celular', models.IntegerField(blank=True, default=0, null=True)),
                ('age_comissao', models.FloatField(max_length=20)),
                ('age_over', models.FloatField(blank=True, default=0, null=True)),
                ('age_markup', models.FloatField(blank=True, default=0, null=True)),
                ('age_banco', models.CharField(choices=[('Caixa', 'Caixa'), ('Bradesco', 'Bradesco'), ('Santander', 'Santander')], default='Caixa', max_length=20)),
                ('age_agencia', models.IntegerField(blank=True, default=0, null=True)),
                ('age_conta', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('agt_codigo', models.AutoField(primary_key=True, serialize=False)),
                ('age_codigo', models.CharField(max_length=255)),
                ('agt_descricao', models.CharField(max_length=255)),
                ('agt_cpf', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
            ],
        ),
    ]
